import type { Metadata, Viewport } from "next";
import nextDynamic from "next/dynamic";
import { headers } from "next/headers";
import type { ReactNode } from "react";

import { AppShell } from "@/components/app-shell";
import { LocaleProvider } from "@/components/locale-provider";
import { Providers } from "@/components/providers";
import { localeCopy } from "@/lib/locale";
import { getRequestLocale } from "@/lib/locale-server";
import { scaleEvidenceServerConfig } from "@/lib/scale-evidence-server";
import { PUBLIC_BRAND } from "@/lib/brand";

import "./globals.css";

const legacyStyleSheets = [
  "/styles/product-shell.css",
  "/styles/enterprise-refresh.css",
  "/styles/structara.css",
  "/styles/structara-legal.css",
  "/styles/structara-sec-proof.css",
  "/styles/structara-security.css",
  "/styles/folynta.css",
] as const;

const ScaleEvidenceBridge = nextDynamic(() =>
  import("@/components/system/scale-evidence-bridge").then(
    (module) => module.ScaleEvidenceBridge,
  ),
);

// Per-request CSP nonces are generated by src/proxy.ts, so HTML must be
// rendered at request time rather than reused with a stale nonce.
export const dynamic = "force-dynamic";

export async function generateMetadata(): Promise<Metadata> {
  const locale = await getRequestLocale();
  const title = localeCopy(locale, {
    en: `${PUBLIC_BRAND.name} — ${PUBLIC_BRAND.category}`,
    ko: `${PUBLIC_BRAND.name} — 지식 컴파일러`,
  });
  const description = localeCopy(locale, {
    en: "Turn documents into structured, verified, connected, and portable knowledge for people and AI.",
    ko: "문서를 사람과 AI가 함께 사용할 수 있는 구조화·검증·연결·이식 가능한 지식으로 전환합니다.",
  });
  const socialDescription = localeCopy(locale, {
    en: "Structured, verified, connected, portable knowledge with every important result linked to its source.",
    ko: "모든 핵심 결과가 원문 근거와 연결되는 구조화·검증·연결·이식 가능한 지식.",
  });

  return {
    metadataBase: new URL(
      process.env.NEXT_PUBLIC_SITE_URL ?? "http://127.0.0.1:3000",
    ),
    title: {
      default: title,
      template: `%s · ${PUBLIC_BRAND.name}`,
    },
    description,
    applicationName: PUBLIC_BRAND.name,
    keywords:
      locale === "ko"
        ? [
            "지식 컴파일러",
            "문서 인텔리전스",
            "출처 추적",
            "검증된 지식",
            "RAG 준비",
          ]
        : [
            "knowledge compiler",
            "document intelligence",
            "source provenance",
            "verified knowledge",
            "RAG preparation",
          ],
    authors: [{ name: PUBLIC_BRAND.name }],
    creator: PUBLIC_BRAND.name,
    publisher: PUBLIC_BRAND.name,
    robots: { index: true, follow: true },
    openGraph: {
      type: "website",
      siteName: PUBLIC_BRAND.name,
      title,
      description: socialDescription,
      locale: locale === "ko" ? "ko_KR" : "en_US",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  colorScheme: "light dark",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f5f3ee" },
    { media: "(prefers-color-scheme: dark)", color: "#080a0f" },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  const locale = await getRequestLocale();
  const pathname = (await headers()).get("x-folynta-pathname") ?? "/";
  const includeLegacyStyles = pathname !== "/";
  const scaleEvidenceConfig = scaleEvidenceServerConfig(process.env);
  const skipLabel = localeCopy(locale, {
    en: "Skip to main content",
    ko: "본문으로 건너뛰기",
  });

  return (
    <html lang={locale} suppressHydrationWarning>
      {includeLegacyStyles ? (
        <head>
          {legacyStyleSheets.map((href) => (
            <link key={href} rel="stylesheet" href={href} />
          ))}
        </head>
      ) : null}
      <body>
        <a className="skip-link" href="#main-content">
          {skipLabel}
        </a>
        <LocaleProvider locale={locale}>
          <Providers>
            {scaleEvidenceConfig.enabled === "true" ? (
              <ScaleEvidenceBridge config={scaleEvidenceConfig} />
            ) : null}
            <AppShell>{children}</AppShell>
          </Providers>
        </LocaleProvider>
      </body>
    </html>
  );
}
