import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";

import { AppShell } from "@/components/app-shell";
import { Providers } from "@/components/providers";

import "./globals.css";
import "./product-shell.css";
import "./enterprise-refresh.css";

// Per-request CSP nonces are generated by src/proxy.ts, so HTML must be
// rendered at request time rather than reused with a stale nonce.
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: {
    default: "AI Knowledge Compiler",
    template: "%s · AI Knowledge Compiler",
  },
  description:
    "Compile documents into source-grounded Markdown, Obsidian Vaults, RAG data, and knowledge graphs.",
  applicationName: "AI Knowledge Compiler",
  robots: { index: false, follow: false },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  colorScheme: "light dark",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f6f7f9" },
    { media: "(prefers-color-scheme: dark)", color: "#0d1117" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <a className="skip-link" href="#main-content">
          Skip to main content
        </a>
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}
