import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";

import { AppShell } from "@/components/app-shell";
import { Providers } from "@/components/providers";

import "./globals.css";

// Per-request CSP nonces are generated by src/proxy.ts, so HTML must be
// rendered at request time rather than reused with a stale nonce.
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: {
    default: "AI Knowledge Compiler",
    template: "%s · AI Knowledge Compiler",
  },
  description:
    "문서에서 원문 근거가 연결된 Portable Markdown, Obsidian Vault, RAG 데이터와 지식 그래프를 컴파일합니다.",
  applicationName: "AI Knowledge Compiler",
  robots: { index: false, follow: false },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  colorScheme: "light dark",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f6f7f9" },
    { media: "(prefers-color-scheme: dark)", color: "#0d1117" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        <a className="skip-link" href="#main-content">
          본문으로 바로가기
        </a>
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}
