"""Deterministic routing and preflight policy."""

from .calibration import CalibrationBin, expected_calibration_error
from .champion_matrix import ChampionCandidate, ChampionMatrix
from .engine import decide_escalation, estimate_route_credits, select_first_route
from .estimation import (
    ClusterSamplePlan,
    CollectionEstimate,
    CollectionEstimateInput,
    DimensionUnit,
    EstimateCalibration,
    EstimateConfidence,
    GpuClass,
    GpuThermalState,
    LearnedRouterShadowRecord,
    PreflightObservation,
    RoutePopulation,
    StaticDocumentFeatures,
    build_cluster_identity,
    build_zero_authority_learned_router_shadow,
    calibrate_estimate,
    estimate_collection,
    select_adaptive_samples,
)
from .expected_verified_cost import RouteCostCandidate, select_expected_verified_cost
from .models import (
    MODE_PROFILE,
    DataPolicy,
    EscalationAction,
    EscalationDecision,
    FeatureFlags,
    ProcessingMode,
    QualitySignal,
    Route,
    RouteDecision,
    RouteProfile,
    RouterContext,
    RoutingAudit,
)
from .preflight import (
    DocumentMetrics,
    PageMetrics,
    PageTechnicalClass,
    RiskTier,
    classify_page,
    detect_script_distribution,
    native_candidate,
    native_requires_visual_cross_check,
    preflight_difficulty,
)
from .providers import (
    KnowledgeProvider,
    KnowledgeRequest,
    KnowledgeResult,
    ParserCapabilities,
    ParseRequest,
    ParseResult,
    ParserProvider,
    ProviderRegistry,
    ProviderUnavailableError,
)
from .research import (
    BetaBinomialPosterior,
    CandidateForecast,
    MonteCarloScheduleEstimate,
    ScheduleScenario,
    SelectiveRouteDecision,
    estimate_schedule,
    select_risk_constrained_candidate,
)

__all__ = [
    "MODE_PROFILE",
    "BetaBinomialPosterior",
    "CalibrationBin",
    "CandidateForecast",
    "ChampionCandidate",
    "ChampionMatrix",
    "ClusterSamplePlan",
    "CollectionEstimate",
    "CollectionEstimateInput",
    "DataPolicy",
    "DimensionUnit",
    "DocumentMetrics",
    "EscalationAction",
    "EscalationDecision",
    "EstimateCalibration",
    "EstimateConfidence",
    "FeatureFlags",
    "GpuClass",
    "GpuThermalState",
    "KnowledgeProvider",
    "KnowledgeRequest",
    "KnowledgeResult",
    "LearnedRouterShadowRecord",
    "MonteCarloScheduleEstimate",
    "PageMetrics",
    "PageTechnicalClass",
    "ParseRequest",
    "ParseResult",
    "ParserCapabilities",
    "ParserProvider",
    "PreflightObservation",
    "ProcessingMode",
    "ProviderRegistry",
    "ProviderUnavailableError",
    "QualitySignal",
    "RiskTier",
    "Route",
    "RouteCostCandidate",
    "RouteDecision",
    "RoutePopulation",
    "RouteProfile",
    "RouterContext",
    "RoutingAudit",
    "ScheduleScenario",
    "SelectiveRouteDecision",
    "StaticDocumentFeatures",
    "build_cluster_identity",
    "build_zero_authority_learned_router_shadow",
    "calibrate_estimate",
    "classify_page",
    "decide_escalation",
    "detect_script_distribution",
    "estimate_collection",
    "estimate_route_credits",
    "estimate_schedule",
    "expected_calibration_error",
    "native_candidate",
    "native_requires_visual_cross_check",
    "preflight_difficulty",
    "select_adaptive_samples",
    "select_expected_verified_cost",
    "select_first_route",
    "select_risk_constrained_candidate",
]
