"""Deterministic routing and preflight policy."""

from .engine import decide_escalation, estimate_route_credits, select_first_route
from .models import (
    MODE_PROFILE,
    DataPolicy,
    EscalationAction,
    EscalationDecision,
    FeatureFlags,
    ProcessingMode,
    QualitySignal,
    Route,
    RouteDecision,
    RouteProfile,
    RouterContext,
    RoutingAudit,
)
from .preflight import (
    DocumentMetrics,
    PageMetrics,
    PageTechnicalClass,
    RiskTier,
    classify_page,
    detect_script_distribution,
    native_candidate,
    native_requires_visual_cross_check,
    preflight_difficulty,
)
from .providers import (
    KnowledgeProvider,
    KnowledgeRequest,
    KnowledgeResult,
    ParserCapabilities,
    ParseRequest,
    ParseResult,
    ParserProvider,
    ProviderRegistry,
    ProviderUnavailableError,
)

__all__ = [
    "MODE_PROFILE",
    "DataPolicy",
    "DocumentMetrics",
    "EscalationAction",
    "EscalationDecision",
    "FeatureFlags",
    "KnowledgeProvider",
    "KnowledgeRequest",
    "KnowledgeResult",
    "PageMetrics",
    "PageTechnicalClass",
    "ParseRequest",
    "ParseResult",
    "ParserCapabilities",
    "ParserProvider",
    "ProcessingMode",
    "ProviderRegistry",
    "ProviderUnavailableError",
    "QualitySignal",
    "RiskTier",
    "Route",
    "RouteDecision",
    "RouteProfile",
    "RouterContext",
    "RoutingAudit",
    "classify_page",
    "decide_escalation",
    "detect_script_distribution",
    "estimate_route_credits",
    "native_candidate",
    "native_requires_visual_cross_check",
    "preflight_difficulty",
    "select_first_route",
]
