"""Core contracts for the arena campaign: ids, receipts, errors, states.

Every other lane depends on this package and on nothing of theirs. The four
modules answer four questions that must have exactly one answer each:

- ``ids``      what is this thing called, and does the name follow from frozen inputs?
- ``errors``   what kind of failure was that, and is retrying it worth money?
- ``states``   is this transition legal?
- ``receipts`` may these bytes be written, and do they satisfy their schema?
"""

from __future__ import annotations

from arena.core.authorizations import (
    AuthorizationError,
    AuthorizationReceipt,
    load_authorizations,
    parse_authorization,
    select_authorization,
)
from arena.core.errors import (
    RETRY_POLICY,
    RETRY_POLICY_NOTES,
    BackoffKind,
    ErrorClass,
    RetryRule,
    classify_failure,
    is_retryable,
    retry_rule,
)
from arena.core.ids import (
    RECOVERY_TYPES,
    SHARD_INDEX_WIDTH,
    IdError,
    bootstrap_image_digest,
    canonical_json,
    canonical_json_bytes,
    case_key_from_staged,
    inference_job_id,
    recovery_job_id,
    sample_id_from_staged,
    sha256_file,
    sha256_hex,
    sha256_ref,
    shard_id,
    strip_source_extension,
    worker_id,
)
from arena.core.receipts import (
    CANARY_CRITERIA,
    SCHEMA_NAMES,
    SCHEMAS_DIR,
    SEMANTIC_ERROR_CLASSES,
    AuthorizationReceiptRecord,
    CanaryCriterion,
    CanaryCriterionId,
    CanaryReceipt,
    CanonicalPayload,
    ConcurrencyPolicy,
    ErrorRecord,
    EvaluatorRegistryRecord,
    Event,
    FrozenManifest,
    HeartbeatReport,
    LatencyQuantiles,
    LicenseRef,
    ModelRegistryRecord,
    PageReceipt,
    PodLedgerEntry,
    RawOutputPayload,
    ReadyResponse,
    ReceiptError,
    RecoveryJob,
    RouteDecision,
    RunSummary,
    RuntimeSpec,
    SchemaValidationError,
    SecretMaterialError,
    TimingsMs,
    WeightsRef,
    WorkerRunRequest,
    WorkerRunResponse,
    append_jsonl,
    assert_secret_free,
    iter_jsonl,
    load_schema,
    model_for_schema,
    read_jsonl,
    record_sha256,
    schema_name_for_id,
    utc_timestamp,
    validate,
    write_atomic_json,
)
from arena.core.states import (
    ALLOWED_CONTROLLER_TRANSITIONS,
    ALLOWED_TRANSITIONS,
    ALLOWED_WORKER_TRANSITIONS,
    ControllerState,
    IllegalTransition,
    StateMachineKind,
    WorkerState,
    allowed_transitions,
    is_terminal,
    transition,
)

__all__ = [
    "ALLOWED_CONTROLLER_TRANSITIONS",
    "ALLOWED_TRANSITIONS",
    "ALLOWED_WORKER_TRANSITIONS",
    "CANARY_CRITERIA",
    "RECOVERY_TYPES",
    "RETRY_POLICY",
    "RETRY_POLICY_NOTES",
    "SCHEMAS_DIR",
    "SCHEMA_NAMES",
    "SEMANTIC_ERROR_CLASSES",
    "SHARD_INDEX_WIDTH",
    "AuthorizationError",
    "AuthorizationReceipt",
    "AuthorizationReceiptRecord",
    "BackoffKind",
    "CanaryCriterion",
    "CanaryCriterionId",
    "CanaryReceipt",
    "CanonicalPayload",
    "ConcurrencyPolicy",
    "ControllerState",
    "ErrorClass",
    "ErrorRecord",
    "EvaluatorRegistryRecord",
    "Event",
    "FrozenManifest",
    "HeartbeatReport",
    "IdError",
    "IllegalTransition",
    "LatencyQuantiles",
    "LicenseRef",
    "ModelRegistryRecord",
    "PageReceipt",
    "PodLedgerEntry",
    "RawOutputPayload",
    "ReadyResponse",
    "ReceiptError",
    "RecoveryJob",
    "RetryRule",
    "RouteDecision",
    "RunSummary",
    "RuntimeSpec",
    "SchemaValidationError",
    "SecretMaterialError",
    "StateMachineKind",
    "TimingsMs",
    "WeightsRef",
    "WorkerRunRequest",
    "WorkerRunResponse",
    "WorkerState",
    "allowed_transitions",
    "append_jsonl",
    "assert_secret_free",
    "bootstrap_image_digest",
    "canonical_json",
    "canonical_json_bytes",
    "case_key_from_staged",
    "classify_failure",
    "inference_job_id",
    "is_retryable",
    "is_terminal",
    "iter_jsonl",
    "load_authorizations",
    "load_schema",
    "model_for_schema",
    "parse_authorization",
    "read_jsonl",
    "record_sha256",
    "recovery_job_id",
    "retry_rule",
    "sample_id_from_staged",
    "schema_name_for_id",
    "select_authorization",
    "sha256_file",
    "sha256_hex",
    "sha256_ref",
    "shard_id",
    "strip_source_extension",
    "transition",
    "utc_timestamp",
    "validate",
    "worker_id",
    "write_atomic_json",
]
