/* AUTO-GENERATED by scripts/generate_contract_types.py. DO NOT EDIT. */

export type GeneratedJsonPrimitive = string | number | boolean | null;
export type GeneratedJsonValue =
  | GeneratedJsonPrimitive
  | ReadonlyArray<GeneratedJsonValue>
  | Readonly<{ [key: string]: GeneratedJsonValue }>;

export namespace CanonicalDocumentContract {
  export type BBox1000 = readonly [number, number, number, number];
  export type BlockOrigin = "native_extracted" | "ocr_extracted" | "rule_reconstructed" | "ai_reconstructed" | "ai_summarized" | "ai_inferred" | "user_edited";
  export type BlockType = "title" | "heading" | "paragraph" | "list" | "table" | "figure" | "caption" | "formula" | "code" | "quote" | "footnote" | "header" | "footer" | "page_number" | "unknown";
  export type CanonicalBlock = { readonly id: string; readonly parentId?: string | null; readonly order: number; readonly type: BlockType; readonly contentLayer: ContentLayer; readonly rawText?: string | null; readonly normalizedText?: string | null; readonly markdown?: string | null; readonly sanitizedHtml?: string | null; readonly table?: CanonicalTable | null; readonly formulaLatex?: string | null; readonly origin: BlockOrigin; readonly sourceRefs: ReadonlyArray<SourceRef>; readonly modelRunIds?: ReadonlyArray<string>; readonly confidence?: number | null; readonly qualityFlags?: ReadonlyArray<string>; readonly contentHash: string; readonly revision?: number; };
  export type CanonicalCell = { readonly id: string; readonly rowIndex0: number; readonly columnIndex0: number; readonly rowSpan?: number; readonly columnSpan?: number; readonly rawText?: string; readonly normalizedText?: string; readonly origin: BlockOrigin; readonly sourceRefs: ReadonlyArray<SourceRef>; readonly confidence?: number | null; readonly qualityFlags?: ReadonlyArray<string>; };
  export type CanonicalTable = { readonly id: string; readonly rowCount: number; readonly columnCount: number; readonly headerRowCount?: number; readonly cells: ReadonlyArray<CanonicalCell>; readonly caption?: string | null; readonly sourceRefs: ReadonlyArray<SourceRef>; readonly qualityFlags?: ReadonlyArray<string>; };
  export type ContentLayer = "source" | "extracted" | "structured" | "knowledge" | "index";
  export type ModelRunRecord = { readonly id: string; readonly provider: string; readonly model: string; readonly revision: string; readonly runtime: string; readonly runtimeVersion: string; readonly promptSha256: string; readonly quantization?: string | null; readonly hardware: string; readonly containerDigest: string; readonly routeProfile: string; readonly startedAt: string; readonly completedAt?: string | null; };
  export type SourceRef = { readonly documentId: string; readonly documentVersionId: string; readonly pageIndex0: number; readonly pageNumber1: number; readonly bbox1000?: BBox1000 | null; readonly nativeObjectId?: string | null; readonly imageAssetId?: string | null; readonly timeStartMs?: number | null; readonly timeEndMs?: number | null; };
  export type Root = { readonly schemaVersion?: string; readonly tenantId: string; readonly documentId: string; readonly documentVersionId: string; readonly title: string; readonly sourceFilename: string; readonly sourceSha256: string; readonly contentLayer: ContentLayer; readonly blocks: ReadonlyArray<CanonicalBlock>; readonly modelRuns?: ReadonlyArray<ModelRunRecord>; readonly metadata?: {  } & Readonly<Record<string, GeneratedJsonValue>>; readonly createdAt: string; };
}
export type CanonicalDocumentGenerated = CanonicalDocumentContract.Root;

export namespace CanonicalTableContract {
  export type BBox1000 = readonly [number, number, number, number];
  export type BlockOrigin = "native_extracted" | "ocr_extracted" | "rule_reconstructed" | "ai_reconstructed" | "ai_summarized" | "ai_inferred" | "user_edited";
  export type CanonicalCell = { readonly id: string; readonly rowIndex0: number; readonly columnIndex0: number; readonly rowSpan?: number; readonly columnSpan?: number; readonly rawText?: string; readonly normalizedText?: string; readonly origin: BlockOrigin; readonly sourceRefs: ReadonlyArray<SourceRef>; readonly confidence?: number | null; readonly qualityFlags?: ReadonlyArray<string>; };
  export type SourceRef = { readonly documentId: string; readonly documentVersionId: string; readonly pageIndex0: number; readonly pageNumber1: number; readonly bbox1000?: BBox1000 | null; readonly nativeObjectId?: string | null; readonly imageAssetId?: string | null; readonly timeStartMs?: number | null; readonly timeEndMs?: number | null; };
  export type Root = { readonly id: string; readonly rowCount: number; readonly columnCount: number; readonly headerRowCount?: number; readonly cells: ReadonlyArray<CanonicalCell>; readonly caption?: string | null; readonly sourceRefs: ReadonlyArray<SourceRef>; readonly qualityFlags?: ReadonlyArray<string>; };
}
export type CanonicalTableGenerated = CanonicalTableContract.Root;

export namespace DocumentClassificationContract {
  export type DocumentContains = { readonly tables?: boolean; readonly formulas?: boolean; readonly figures?: boolean; readonly citations?: boolean; readonly personalData?: boolean; };
  export type Root = { readonly documentType: string; readonly secondaryTypes?: ReadonlyArray<string>; readonly language: string; readonly languages?: ReadonlyArray<string>; readonly topics?: ReadonlyArray<string>; readonly domain?: ReadonlyArray<string>; readonly structureProfile: string; readonly riskTier: string; readonly contains: DocumentContains; readonly evidenceBlockIds: ReadonlyArray<string>; readonly confidence: number; };
}
export type DocumentClassificationGenerated = DocumentClassificationContract.Root;

export namespace ErrorEnvelopeContract {
  export type ErrorCode = "INVALID_REQUEST" | "UNSUPPORTED_FILE_TYPE" | "FILE_SIGNATURE_MISMATCH" | "FILE_TOO_LARGE" | "FILE_MALICIOUS" | "ARCHIVE_UNSAFE" | "PASSWORD_REQUIRED" | "INVALID_PASSWORD" | "QUOTA_EXCEEDED" | "URL_BLOCKED" | "ROUTE_UNAVAILABLE" | "PROVIDER_TIMEOUT" | "PROVIDER_INVALID_OUTPUT" | "QUALITY_REVIEW_REQUIRED" | "INTERNAL_ERROR";
  export type Root = { readonly schemaVersion?: string; readonly code: ErrorCode; readonly message: string; readonly retryable?: boolean; readonly traceId: string; readonly details?: {  } & Readonly<Record<string, GeneratedJsonValue>>; };
}
export type ErrorEnvelopeGenerated = ErrorEnvelopeContract.Root;

export namespace ExportManifestContract {
  export type ExportFile = { readonly path: string; readonly mediaType: string; readonly sha256: string; readonly sizeBytes: number; };
  export type ExportProfile = "bundle" | "portable_raw" | "portable_structured" | "obsidian" | "rag" | "json_ld";
  export type Root = { readonly schemaVersion?: string; readonly exportId: string; readonly tenantId: string; readonly projectId: string; readonly documentId: string; readonly documentVersionId: string; readonly profile: ExportProfile; readonly sourceSha256: string; readonly generatedAt: string; readonly files: ReadonlyArray<ExportFile>; readonly modelProvenance?: {  } & Readonly<Record<string, GeneratedJsonValue>>; readonly warnings?: ReadonlyArray<string>; };
}
export type ExportManifestGenerated = ExportManifestContract.Root;

export namespace KnowledgeBundleContract {
  export type AssertionStatus = "extracted" | "ai_summarized" | "ai_inferred" | "user_verified";
  export type BlockOrigin = "native_extracted" | "ocr_extracted" | "rule_reconstructed" | "ai_reconstructed" | "ai_summarized" | "ai_inferred" | "user_edited";
  export type Claim = { readonly text: string; readonly origin: BlockOrigin; readonly sourceBlockIds: ReadonlyArray<string>; readonly confidence: number; };
  export type ConflictCandidate = { readonly id: string; readonly statementA: {  } & Readonly<Record<string, GeneratedJsonValue>>; readonly statementB: {  } & Readonly<Record<string, GeneratedJsonValue>>; readonly dimension: ConflictDimension; readonly resolution?: string; readonly requiresReview?: boolean; readonly evidenceBlockIds: ReadonlyArray<string>; };
  export type ConflictDimension = "version_or_time" | "contradictory_claim" | "definition" | "numeric_value" | "other";
  export type KnowledgeNote = { readonly noteId: string; readonly title: string; readonly noteType: NoteType; readonly contentOrigin: BlockOrigin; readonly evidenceBlockIds: ReadonlyArray<string>; readonly summary?: string | null; readonly claims: ReadonlyArray<Claim>; readonly aliases?: ReadonlyArray<string>; readonly tags?: ReadonlyArray<string>; readonly relatedNoteCandidates?: ReadonlyArray<RelatedNoteCandidate>; readonly reviewStatus?: ReviewStatus; };
  export type NoteType = "concept" | "document" | "person" | "organization" | "project" | "glossary" | "question" | "moc";
  export type RelatedNoteCandidate = { readonly targetId: string; readonly relation: string; readonly reason: string; readonly sourceBlockIds: ReadonlyArray<string>; readonly confidence: number; };
  export type RelationAssertion = { readonly id: string; readonly subject: string; readonly predicate: string; readonly object: string; readonly assertionStatus: AssertionStatus; readonly confidence: number; readonly evidenceBlockIds: ReadonlyArray<string>; readonly reviewStatus?: ReviewStatus; };
  export type ReviewStatus = "pending" | "auto_with_warnings" | "user_verified" | "rejected";
  export type Root = { readonly schemaVersion?: string; readonly documentId: string; readonly notes: ReadonlyArray<KnowledgeNote>; readonly relations?: ReadonlyArray<RelationAssertion>; readonly conflicts?: ReadonlyArray<ConflictCandidate>; };
}
export type KnowledgeBundleGenerated = KnowledgeBundleContract.Root;

export namespace KnowledgeNoteContract {
  export type BlockOrigin = "native_extracted" | "ocr_extracted" | "rule_reconstructed" | "ai_reconstructed" | "ai_summarized" | "ai_inferred" | "user_edited";
  export type Claim = { readonly text: string; readonly origin: BlockOrigin; readonly sourceBlockIds: ReadonlyArray<string>; readonly confidence: number; };
  export type NoteType = "concept" | "document" | "person" | "organization" | "project" | "glossary" | "question" | "moc";
  export type RelatedNoteCandidate = { readonly targetId: string; readonly relation: string; readonly reason: string; readonly sourceBlockIds: ReadonlyArray<string>; readonly confidence: number; };
  export type ReviewStatus = "pending" | "auto_with_warnings" | "user_verified" | "rejected";
  export type Root = { readonly noteId: string; readonly title: string; readonly noteType: NoteType; readonly contentOrigin: BlockOrigin; readonly evidenceBlockIds: ReadonlyArray<string>; readonly summary?: string | null; readonly claims: ReadonlyArray<Claim>; readonly aliases?: ReadonlyArray<string>; readonly tags?: ReadonlyArray<string>; readonly relatedNoteCandidates?: ReadonlyArray<RelatedNoteCandidate>; readonly reviewStatus?: ReviewStatus; };
}
export type KnowledgeNoteGenerated = KnowledgeNoteContract.Root;

export namespace ProcessingEventContract {
  export type EventType = "job.created.v1" | "job.stage.started.v1" | "job.stage.progress.v1" | "job.stage.completed.v1" | "page.preflight.completed.v1" | "page.route.selected.v1" | "page.processing.started.v1" | "page.layout.detected.v1" | "page.block.completed.v1" | "page.markdown.updated.v1" | "page.quality.updated.v1" | "page.retry.scheduled.v1" | "page.completed.v1" | "page.needs_review.v1" | "page.failed.v1" | "document.knowledge.note_created.v1" | "document.knowledge.link_created.v1" | "document.validation.completed.v1" | "export.started.v1" | "export.completed.v1" | "job.completed.v1" | "job.failed.v1" | "job.cancelled.v1" | "credit.reserved.v1" | "credit.consumed.v1" | "credit.released.v1";
  export type Root = { readonly schema_version?: "1.0"; readonly event_id: string; readonly event_type: EventType; readonly sequence: number; readonly occurred_at: string; readonly project_id: string; readonly job_id: string; readonly tenant_id?: string | null; readonly document_id?: string | null; readonly document_version_id?: string | null; readonly page_id?: string | null; readonly payload?: {  } & Readonly<Record<string, GeneratedJsonValue>>; };
}
export type ProcessingEventGenerated = ProcessingEventContract.Root;

export namespace QualityReportContract {
  export type Root = { readonly schemaVersion?: string; readonly documentId: string; readonly overallScore: number; readonly status: string; readonly componentScores: {  } & Readonly<Record<string, number>>; readonly findings?: ReadonlyArray<{  } & Readonly<Record<string, GeneratedJsonValue>>>; readonly reviewItemCount?: number; };
}
export type QualityReportGenerated = QualityReportContract.Root;

export namespace RagChunkContract {
  export type BBox1000 = readonly [number, number, number, number];
  export type BlockOrigin = "native_extracted" | "ocr_extracted" | "rule_reconstructed" | "ai_reconstructed" | "ai_summarized" | "ai_inferred" | "user_edited";
  export type ContentLayer = "source" | "extracted" | "structured" | "knowledge" | "index";
  export type SourceRef = { readonly documentId: string; readonly documentVersionId: string; readonly pageIndex0: number; readonly pageNumber1: number; readonly bbox1000?: BBox1000 | null; readonly nativeObjectId?: string | null; readonly imageAssetId?: string | null; readonly timeStartMs?: number | null; readonly timeEndMs?: number | null; };
  export type Root = { readonly schemaVersion?: string; readonly chunkId: string; readonly documentId: string; readonly documentVersion: string; readonly title: string; readonly headingPath: ReadonlyArray<string>; readonly content: string; readonly contentType: string; readonly language: string; readonly tokenCount: number; readonly tokenizer: string; readonly sourceRefs: ReadonlyArray<SourceRef>; readonly origin: BlockOrigin; readonly contentLayer: ContentLayer; readonly quality?: number | null; readonly previousChunkId?: string | null; readonly nextChunkId?: string | null; readonly contentHash: string; };
}
export type RagChunkGenerated = RagChunkContract.Root;

export namespace RelationAssertionContract {
  export type AssertionStatus = "extracted" | "ai_summarized" | "ai_inferred" | "user_verified";
  export type ReviewStatus = "pending" | "auto_with_warnings" | "user_verified" | "rejected";
  export type Root = { readonly id: string; readonly subject: string; readonly predicate: string; readonly object: string; readonly assertionStatus: AssertionStatus; readonly confidence: number; readonly evidenceBlockIds: ReadonlyArray<string>; readonly reviewStatus?: ReviewStatus; };
}
export type RelationAssertionGenerated = RelationAssertionContract.Root;

export namespace SourceMapContract {
  export type BBox1000 = readonly [number, number, number, number];
  export type BlockOrigin = "native_extracted" | "ocr_extracted" | "rule_reconstructed" | "ai_reconstructed" | "ai_summarized" | "ai_inferred" | "user_edited";
  export type MarkdownRange = { readonly startLine1: number; readonly endLine1: number; readonly startCodepoint0: number; readonly endCodepoint0: number; readonly offsetEncoding?: string; };
  export type SourceMapEntry = { readonly blockId: string; readonly revision: number; readonly contentHash: string; readonly markdownPath: string; readonly markdownRange: MarkdownRange; readonly sourceRefs: ReadonlyArray<SourceRef>; readonly origin: BlockOrigin; readonly confidence?: number | null; };
  export type SourceRef = { readonly documentId: string; readonly documentVersionId: string; readonly pageIndex0: number; readonly pageNumber1: number; readonly bbox1000?: BBox1000 | null; readonly nativeObjectId?: string | null; readonly imageAssetId?: string | null; readonly timeStartMs?: number | null; readonly timeEndMs?: number | null; };
  export type Root = { readonly schemaVersion?: string; readonly documentId: string; readonly documentVersionId: string; readonly sourceSha256: string; readonly entries: ReadonlyArray<SourceMapEntry>; };
}
export type SourceMapGenerated = SourceMapContract.Root;
