"""Deterministic compilers from CIR to portable output profiles."""

from .chunks import Tokenizer, UnicodeEstimateTokenizer, adaptive_chunks
from .filenames import (
    collision_key,
    portable_slug,
    stable_markdown_filename,
    with_collision_suffix,
)
from .jsonld import (
    AKMP_CONTEXT,
    KNOWLEDGE_NOTE_SHACL,
    chunks_jsonl,
    context_jsonld,
    documents_jsonl,
    knowledge_jsonld,
)
from .knowledge_package import (
    Ed25519Signer,
    Ed25519Verifier,
    ImportedKnowledgePackage,
    KnowledgePackageError,
    KnowledgePackageReceipt,
    KnowledgePackageSemanticProfile,
    PackageSigner,
    PackageVerifier,
    SemanticAssetManifest,
    SemanticBlueprintManifest,
    build_knowledge_package,
    canonical_knowledge_model_bytes,
    import_knowledge_package,
    knowledge_package_semantic_profile,
)
from .markdown import (
    MarkdownArtifact,
    MarkdownExportOptions,
    export_markdown,
    source_map_json,
)
from .package import deterministic_zip
from .tables import table_to_csv, table_to_gfm, table_to_html
from .vault import (
    BrokenVaultLink,
    MergePolicy,
    VaultConflict,
    VaultMergePlan,
    compile_vault,
    plan_vault_merge,
    validate_internal_links,
)

__all__ = [
    "AKMP_CONTEXT",
    "KNOWLEDGE_NOTE_SHACL",
    "BrokenVaultLink",
    "Ed25519Signer",
    "Ed25519Verifier",
    "ImportedKnowledgePackage",
    "KnowledgePackageError",
    "KnowledgePackageReceipt",
    "KnowledgePackageSemanticProfile",
    "MarkdownArtifact",
    "MarkdownExportOptions",
    "MergePolicy",
    "PackageSigner",
    "PackageVerifier",
    "SemanticAssetManifest",
    "SemanticBlueprintManifest",
    "Tokenizer",
    "UnicodeEstimateTokenizer",
    "VaultConflict",
    "VaultMergePlan",
    "adaptive_chunks",
    "build_knowledge_package",
    "canonical_knowledge_model_bytes",
    "chunks_jsonl",
    "collision_key",
    "compile_vault",
    "context_jsonld",
    "deterministic_zip",
    "documents_jsonl",
    "export_markdown",
    "import_knowledge_package",
    "knowledge_jsonld",
    "knowledge_package_semantic_profile",
    "plan_vault_merge",
    "portable_slug",
    "source_map_json",
    "stable_markdown_filename",
    "table_to_csv",
    "table_to_gfm",
    "table_to_html",
    "validate_internal_links",
    "with_collision_suffix",
]
