/**
 * Asset manifest and licence gate — MANUS brief §17.4 and §31.
 *
 * §31 states the release rule as a boolean:
 *
 *     production_asset_used AND third_party_asset AND no_manifest_entry
 *     => BUILD / RELEASE FAIL
 *
 * Implementing that literally would need the build to know which files are
 * third-party, and the only thing it can actually see is a file on disk. A
 * gate that has to guess is a gate that fails open: drop a Pexels clip into
 * `public/assets/reality/` with no entry and nothing knows it was not ours.
 *
 * So the rule is inverted and made fail-closed. **Every** file under the asset
 * root needs an entry, and the entry declares its origin. Ours are cheap to
 * declare; third-party ones must carry the full §17.4 receipt. An undeclared
 * file is a violation whatever its origin, which is the same posture the rest
 * of this repository takes on integrity (CLAUDE.md: "fail closed on integrity
 * violations"; "never publish a numerical claim without a receipt").
 */

/** §17.2 — the only sources approved by default. */
export const APPROVED_PROVIDERS = [
  "Pexels",
  "Unsplash",
  "Mixkit",
  "Poly Haven",
  "ambientCG",
  "Fontshare",
  "Lucide",
] as const;

export type ApprovedProvider = (typeof APPROVED_PROVIDERS)[number];

/**
 * §17.3 — sources that may serve as mood reference only. Named explicitly so
 * the gate can reject one by name rather than merely failing to recognise it.
 */
export const REJECTED_PROVIDER_PATTERNS = [
  /google\s*images/i,
  /pinterest/i,
  /dribbble/i,
  /behance/i,
  /sketchfab/i,
  /cgtrader/i,
  /youtube/i,
  /vimeo/i,
] as const;

export type AssetOrigin =
  /** Downloaded from a third party. Requires the full §17.4 receipt. */
  | "third-party"
  /** Generated by our own code — the §19 procedural families. */
  | "procedural"
  /** Synthetic fixture content authored here, e.g. Document Forge output. */
  | "synthetic-fixture";

export type ThirdPartyAsset = {
  readonly asset_id: string;
  readonly local_path: string;
  readonly origin: "third-party";
  readonly source_provider: ApprovedProvider;
  readonly source_url: string;
  readonly author_or_contributor: string;
  readonly license_name: string;
  readonly license_url: string;
  /** ISO date, YYYY-MM-DD. */
  readonly downloaded_at: string;
  readonly commercial_use_checked: boolean;
  readonly third_party_risk: string;
  readonly page_usage: readonly string[];
  readonly transformations: readonly string[];
  readonly approved_by: string;
};

export type OwnAsset = {
  readonly asset_id: string;
  readonly local_path: string;
  readonly origin: "procedural" | "synthetic-fixture";
  /** What generated it, so a stale artifact can be traced to its producer. */
  readonly generated_by: string;
  readonly page_usage: readonly string[];
  /**
   * §17.5 / CLAUDE.md — a synthetic document may never be presented as real
   * evidence. An asset that depicts factual source material must say whether
   * the depiction is real or fabricated.
   */
  readonly depicts_real_evidence: boolean;
};

export type AssetEntry = ThirdPartyAsset | OwnAsset;

export type AssetManifest = {
  readonly version: 1;
  readonly asset_root: string;
  readonly assets: readonly AssetEntry[];
};

export type Violation = {
  readonly kind:
    | "undeclared-file"
    | "missing-file"
    | "missing-field"
    | "unapproved-provider"
    | "rejected-provider"
    | "commercial-use-unchecked"
    | "fabricated-evidence"
    | "duplicate-id";
  readonly subject: string;
  readonly detail: string;
};

const REQUIRED_THIRD_PARTY_FIELDS: readonly (keyof ThirdPartyAsset)[] = [
  "asset_id",
  "local_path",
  "source_provider",
  "source_url",
  "author_or_contributor",
  "license_name",
  "license_url",
  "downloaded_at",
  "commercial_use_checked",
  "third_party_risk",
  "page_usage",
  "transformations",
  "approved_by",
];

const REQUIRED_OWN_FIELDS: readonly (keyof OwnAsset)[] = [
  "asset_id",
  "local_path",
  "generated_by",
  "page_usage",
  "depicts_real_evidence",
];

function isThirdParty(entry: AssetEntry): entry is ThirdPartyAsset {
  return entry.origin === "third-party";
}

/**
 * Validates one entry. Returns violations rather than throwing so the gate can
 * report every problem at once — a licence audit that stops at the first
 * missing field takes as many runs as there are mistakes.
 */
export function validateEntry(entry: AssetEntry): Violation[] {
  const out: Violation[] = [];
  const id = entry.asset_id || entry.local_path || "<unnamed>";

  if (isThirdParty(entry)) {
    for (const field of REQUIRED_THIRD_PARTY_FIELDS) {
      const value = entry[field];
      const empty =
        value === undefined ||
        value === null ||
        value === "" ||
        (Array.isArray(value) && value.length === 0);
      // `commercial_use_checked: false` is a real answer, not an empty field.
      if (empty && field !== "commercial_use_checked") {
        out.push({
          kind: "missing-field",
          subject: id,
          detail: `§17.4 requires "${field}".`,
        });
      }
    }

    if (
      entry.source_provider &&
      !APPROVED_PROVIDERS.includes(entry.source_provider)
    ) {
      out.push({
        kind: "unapproved-provider",
        subject: id,
        detail:
          `"${entry.source_provider}" is not in the §17.2 approved stack. ` +
          `Adding one is a licensing decision, not a config change.`,
      });
    }

    for (const pattern of REJECTED_PROVIDER_PATTERNS) {
      if (pattern.test(entry.source_url ?? "")) {
        out.push({
          kind: "rejected-provider",
          subject: id,
          detail:
            `source_url matches ${pattern}, which §17.3 allows as mood ` +
            `reference only — never as a production asset.`,
        });
      }
    }

    if (entry.commercial_use_checked !== true) {
      out.push({
        kind: "commercial-use-unchecked",
        subject: id,
        detail:
          "commercial_use_checked is not true. An unchecked licence is not a " +
          "cleared one, and Mixkit in particular ships Free and Restricted " +
          "items under the same roof.",
      });
    }
  } else {
    for (const field of REQUIRED_OWN_FIELDS) {
      const value = entry[field];
      const empty =
        value === undefined ||
        value === null ||
        value === "" ||
        (Array.isArray(value) && value.length === 0);
      if (empty && field !== "depicts_real_evidence") {
        out.push({
          kind: "missing-field",
          subject: id,
          detail: `An own asset requires "${field}".`,
        });
      }
    }

    if (entry.origin === "synthetic-fixture" && entry.depicts_real_evidence) {
      out.push({
        kind: "fabricated-evidence",
        subject: id,
        detail:
          "A synthetic fixture cannot depict real evidence. Either it is " +
          "authored — in which case it is not real — or it is a real source " +
          "and does not belong in the fixture set.",
      });
    }
  }

  return out;
}

/**
 * The §31 release gate.
 *
 * `filesOnDisk` are asset-root-relative paths with forward slashes. The caller
 * supplies them because this module has no filesystem access of its own, which
 * also makes the gate testable against a hypothetical tree.
 */
export function auditAssets(
  manifest: AssetManifest,
  filesOnDisk: readonly string[],
): Violation[] {
  const out: Violation[] = [];

  const seen = new Set<string>();
  for (const entry of manifest.assets) {
    if (seen.has(entry.asset_id)) {
      out.push({
        kind: "duplicate-id",
        subject: entry.asset_id,
        detail: "Two entries share one asset_id; one of them is unreachable.",
      });
    }
    seen.add(entry.asset_id);
    out.push(...validateEntry(entry));
  }

  const declared = new Set(manifest.assets.map((a) => normalise(a.local_path)));
  const onDisk = new Set(filesOnDisk.map(normalise));

  for (const file of onDisk) {
    if (!declared.has(file)) {
      out.push({
        kind: "undeclared-file",
        subject: file,
        detail:
          "This file ships but has no manifest entry. Every asset declares " +
          "its origin — the gate cannot tell a stock clip from a rendered " +
          "one by looking at it.",
      });
    }
  }

  for (const path of declared) {
    if (!onDisk.has(path)) {
      out.push({
        kind: "missing-file",
        subject: path,
        detail:
          "Declared in the manifest but absent from disk. A stale entry makes " +
          "the ledger read as broader coverage than exists.",
      });
    }
  }

  return out;
}

function normalise(path: string): string {
  return path.replace(/\\/g, "/").replace(/^\.?\//, "");
}

/**
 * Renders `license-ledger.md`, the human-readable half §33 Phase 1 asks for.
 * Generated, never hand-edited — the same rule the claims pack follows.
 */
export function renderLicenseLedger(manifest: AssetManifest): string {
  const third = manifest.assets.filter(isThirdParty);
  const own = manifest.assets.filter((a) => !isThirdParty(a));

  const lines: string[] = [
    "# Licence ledger",
    "",
    "<!-- Generated from src/content/asset-manifest.json. Do not edit by hand. -->",
    "",
    "Every file under the asset root appears here. Third-party assets carry the",
    "full §17.4 receipt; assets generated by this repository record what produced",
    "them. §31 fails the release if a shipped file is missing from the manifest.",
    "",
  ];

  lines.push(`## Third-party assets (${third.length})`, "");
  if (third.length === 0) {
    lines.push(
      "None yet. No stock photography, footage, HDRI, PBR material or font",
      "binary has been brought into the repository.",
      "",
    );
  } else {
    lines.push(
      "| Asset | Provider | Licence | Author | Acquired | Risk note |",
      "|---|---|---|---|---|---|",
    );
    for (const a of third) {
      lines.push(
        `| \`${a.asset_id}\` | ${a.source_provider} | [${a.license_name}](${a.license_url}) | ${a.author_or_contributor} | ${a.downloaded_at} | ${a.third_party_risk} |`,
      );
    }
    lines.push("");
  }

  lines.push(`## Generated in this repository (${own.length})`, "");
  if (own.length === 0) {
    lines.push(
      "None yet. The §19 semantic families currently render from code at",
      "request time rather than from committed artifacts.",
      "",
    );
  } else {
    lines.push("| Asset | Origin | Produced by | Depicts real evidence |", "|---|---|---|---|");
    for (const a of own) {
      const o = a as OwnAsset;
      lines.push(
        `| \`${o.asset_id}\` | ${o.origin} | ${o.generated_by} | ${o.depicts_real_evidence ? "yes" : "no"} |`,
      );
    }
    lines.push("");
  }

  return lines.join("\n");
}
