"""MCP client registration artifacts generated by ``akc-desktop init``.

The local MCP server itself lives in packages/local-mcp and speaks stdio
(read-only). What we generate here is the *client-side* snippet an MCP host
such as Claude Desktop consumes, plus a reference config describing how
``akc-desktop serve`` will expose the server.
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path

from .config import DesktopAppConfig

__all__ = ["GeneratedMcpConfig", "write_mcp_artifacts"]


class McpSetupError(RuntimeError):
    pass


@dataclass(frozen=True)
class GeneratedMcpConfig:
    snippet_path: Path
    world_state_dir: Path


def build_claude_desktop_snippet(config: DesktopAppConfig) -> dict[str, object]:
    """mcpServers block for Claude Desktop's claude_desktop_config.json."""
    return {
        "mcpServers": {
            "akc-local-mcp": {
                "command": sys.executable,
                "args": ["-m", "akc_local_mcp"],
                "env": {
                    "AKC_LOCAL_MCP_WORLD_STATE_DIR": str(config.world_store),
                },
            }
        }
    }


def write_mcp_artifacts(config: DesktopAppConfig) -> GeneratedMcpConfig:
    """Write the stdio registration snippet under <home>/mcp/."""
    config.mcp_dir.mkdir(parents=True, exist_ok=True)
    target = config.mcp_dir / "claude-desktop-snippet.json"
    payload = build_claude_desktop_snippet(config)
    tmp = target.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(tmp, target)
    return GeneratedMcpConfig(snippet_path=target, world_state_dir=config.world_store)
