"""Fail-closed boundaries for untrusted documents and URLs."""

from .cdr import (
    CdrAdapter,
    CdrRequest,
    CdrResult,
    CdrStatus,
    UnavailableCdrAdapter,
    validate_cdr_result,
)
from .files import (
    ALLOWED_EXTENSIONS,
    BLOCKED_EXTENSIONS,
    PLAN_LIMITS,
    FileValidationResult,
    PlanTier,
    UnsafeFileError,
    UploadLimits,
    require_valid_upload,
    safe_relative_path,
    sanitize_display_filename,
    tenant_object_key,
    validate_upload_bytes,
    validate_upload_stream,
)
from .markup import (
    UnsafeMarkupError,
    ensure_portable_markdown_safe,
    escape_csv_formula,
    sanitize_table_html,
)
from .pdf_secrets import (
    InMemoryPdfSecretStore,
    PdfSecretBinding,
    PdfSecretError,
    PdfSecretLease,
    PdfSecretStore,
    RedisPdfSecretStore,
)
from .preview_redaction import (
    NormalizedBox,
    RedactedPreview,
    UnsafePreviewError,
    redact_preview_png,
)
from .prompt_injection import (
    InjectionRisk,
    InjectionSignal,
    PromptInjectionAssessment,
    detect_prompt_injection,
)
from .sensitive_data import (
    RedactionResult,
    SensitiveFinding,
    SensitiveKind,
    SensitiveScan,
    SensitiveSeverity,
    detect_sensitive_data,
    finding_fingerprint,
    mask_sensitive_text,
)
from .urls import (
    UnsafeUrlError,
    UrlValidationResult,
    validate_redirect_chain,
    validate_resolved_url,
)

__all__ = [
    "ALLOWED_EXTENSIONS",
    "BLOCKED_EXTENSIONS",
    "PLAN_LIMITS",
    "CdrAdapter",
    "CdrRequest",
    "CdrResult",
    "CdrStatus",
    "FileValidationResult",
    "InMemoryPdfSecretStore",
    "InjectionRisk",
    "InjectionSignal",
    "NormalizedBox",
    "PdfSecretBinding",
    "PdfSecretError",
    "PdfSecretLease",
    "PdfSecretStore",
    "PlanTier",
    "PromptInjectionAssessment",
    "RedactedPreview",
    "RedactionResult",
    "RedisPdfSecretStore",
    "SensitiveFinding",
    "SensitiveKind",
    "SensitiveScan",
    "SensitiveSeverity",
    "UnavailableCdrAdapter",
    "UnsafeFileError",
    "UnsafeMarkupError",
    "UnsafePreviewError",
    "UnsafeUrlError",
    "UploadLimits",
    "UrlValidationResult",
    "detect_prompt_injection",
    "detect_sensitive_data",
    "ensure_portable_markdown_safe",
    "escape_csv_formula",
    "finding_fingerprint",
    "mask_sensitive_text",
    "redact_preview_png",
    "require_valid_upload",
    "safe_relative_path",
    "sanitize_display_filename",
    "sanitize_table_html",
    "tenant_object_key",
    "validate_cdr_result",
    "validate_redirect_chain",
    "validate_resolved_url",
    "validate_upload_bytes",
    "validate_upload_stream",
]
