steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - infra/product-core/Dockerfile
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE: asia-northeast3-docker.pkg.dev/$PROJECT_ID/tavonel-product-core/product-core:$BUILD_ID
